### PR TITLE
Add optimize CLI join flags `--join-keep-named` and `--join-keep-meshes`

### PR DESCRIPTION
**Pull request by jo-chemla**
https://github.com/donmccurdy/glTF-Transform/issues/1550

Set default values to false like the current join CLI.

### CODE REVIEW

**Review by donmccurdy — COMMENTED** [review]
Thanks @jo-chemla! I'm open to adding these flags — note that they'll need to be passed through in the command implementation below these flag declarations.

**Comment by jo-chemla** [comment]
🤦 
Of course, sorry about that, was a bit distracted. Just pushed a commit that do use these flags as options when pushing the join transform to the array.

**Comment by jo-chemla** [comment]
Should be good to go, tested via `npm install --legacy-peer-deps && npx packages\cli optimize --join-keep-named true input.glb output.gltf` and I confirm the behavior is correct. 

Note the defaults are not displayed anymore in the respective help CLIs.

**Comment by donmccurdy** [comment]
Thanks @jo-chemla! Just as FYI, I think I may rename these flags as `--join-meshes` and `--join-named` before the release (with inverted values).

> Note the defaults are not displayed anymore in the respective help CLIs.

Hm, maybe it just doesn't show defaults whose values are 'false'? Annoying but outside the control of my library at tho moment. 😕 

> tested via npm install --legacy-peer-deps ...

Just curious, is `--legacy-peer-deps` needed for some reason?

**Comment by jo-chemla** [comment]
Thanks for the feedback! 
 - noted for the inversion of `--join-xyz` upon release
 - when I said defaults are not shown, 
 - and the full log of `npm i` without `--legacy-peer-deps` is below, yields conflicting eslint dependencies, full CLI output below

Regarding defaults not printed indeed only those that are true are printed - first I thought this was because the default from code is a constant rather than explicit bool, `default: !JOIN_DEFAULTS.keepNamed,` rather than `default: true,`

image

And for the `npm i` log

```bash
C:\Dev\Iconem\glTF-Transform>npm i
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/eslint-plugin@7.18.0
npm warn Found: eslint@9.7.0
npm warn node_modules/eslint
npm warn   dev eslint@"9.7.0" from the root project
npm warn   4 more (@eslint-community/eslint-utils, eslint-compat-utils, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn node_modules/@typescript-eslint/eslint-plugin
npm warn   @typescript-eslint/eslint-plugin@"7.18.0" from typescript-eslint@7.18.0
npm warn   node_modules/typescript-eslint
npm warn
npm warn Conflicting peer dependency: eslint@8.57.1
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn   node_modules/@typescript-eslint/eslint-plugin
npm warn     @typescript-eslint/eslint-plugin@"7.18.0" from typescript-eslint@7.18.0
npm warn     node_modules/typescript-eslint
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/parser@7.18.0
npm warn Found: eslint@9.7.0
npm warn node_modules/eslint
npm warn   dev eslint@"9.7.0" from the root project
npm warn   4 more (@eslint-community/eslint-utils, eslint-compat-utils, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/parser@7.18.0
npm warn node_modules/@typescript-eslint/parser
npm warn   peer @typescript-eslint/parser@"^7.0.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn   node_modules/@typescript-eslint/eslint-plugin
npm warn   1 more (typescript-eslint)
npm warn
npm warn Conflicting peer dependency: eslint@8.57.1
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/parser@7.18.0
npm warn   node_modules/@typescript-eslint/parser
npm warn     peer @typescript-eslint/parser@"^7.0.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn     node_modules/@typescript-eslint/eslint-plugin
npm warn     1 more (typescript-eslint)
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/type-utils@7.18.0
npm warn Found: eslint@9.7.0
npm warn node_modules/eslint
npm warn   dev eslint@"9.7.0" from the root project
npm warn   4 more (@eslint-community/eslint-utils, eslint-compat-utils, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/type-utils@7.18.0
npm warn node_modules/@typescript-eslint/type-utils
npm warn   @typescript-eslint/type-utils@"7.18.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn   node_modules/@typescript-eslint/eslint-plugin
npm warn
npm warn Conflicting peer dependency: eslint@8.57.1
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/type-utils@7.18.0
npm warn   node_modules/@typescript-eslint/type-utils
npm warn     @typescript-eslint/type-utils@"7.18.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn     node_modules/@typescript-eslint/eslint-plugin
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @typescript-eslint/utils@7.18.0
npm warn Found: eslint@9.7.0
npm warn node_modules/eslint
npm warn   dev eslint@"9.7.0" from the root project
npm warn   4 more (@eslint-community/eslint-utils, eslint-compat-utils, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^8.56.0" from @typescript-eslint/utils@7.18.0
npm warn node_modules/@typescript-eslint/utils
npm warn   @typescript-eslint/utils@"7.18.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn   node_modules/@typescript-eslint/eslint-plugin
npm warn   2 more (@typescript-eslint/type-utils, typescript-eslint)
npm warn
npm warn Conflicting peer dependency: eslint@8.57.1
npm warn node_modules/eslint
npm warn   peer eslint@"^8.56.0" from @typescript-eslint/utils@7.18.0
npm warn   node_modules/@typescript-eslint/utils
npm warn     @typescript-eslint/utils@"7.18.0" from @typescript-eslint/eslint-plugin@7.18.0
npm warn     node_modules/@typescript-eslint/eslint-plugin
npm warn     2 more (@typescript-eslint/type-utils, typescript-eslint)
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: typescript-eslint@7.18.0
npm error Found: eslint@9.7.0
npm error node_modules/eslint
npm error   dev eslint@"9.7.0" from the root project
npm error   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm error   node_modules/@eslint-community/eslint-utils
npm error     @eslint-community/eslint-utils@"^4.4.0" from @typescript-eslint/utils@7.18.0
npm error     node_modules/@typescript-eslint/utils
npm error       @typescript-eslint/utils@"7.18.0" from @typescript-eslint/eslint-plugin@7.18.0
npm error       node_modules/@typescript-eslint/eslint-plugin
npm error         @typescript-eslint/eslint-plugin@"7.18.0" from typescript-eslint@7.18.0
npm error         node_modules/typescript-eslint
npm error       2 more (@typescript-eslint/type-utils, typescript-eslint)
npm error     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.7.0
npm error     1 more (eslint-plugin-svelte)
npm error   3 more (eslint-compat-utils, eslint-config-prettier, eslint-plugin-svelte)
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^8.56.0" from typescript-eslint@7.18.0
npm error node_modules/typescript-eslint
npm error   dev typescript-eslint@"^7.17.0" from the root project
npm error
npm error Conflicting peer dependency: eslint@8.57.1
npm error node_modules/eslint
npm error   peer eslint@"^8.56.0" from typescript-eslint@7.18.0
npm error   node_modules/typescript-eslint
npm error     dev typescript-eslint@"^7.17.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\jonathan\AppData\Local\npm-cache\_logs\2024-11-20T07_53_58_297Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\jonathan\AppData\Local\npm-cache\_logs\2024-11-20T07_53_58_297Z-debug-0.log

```

**Comment by donmccurdy** [comment]
> ... and the full log of npm i without --legacy-peer-deps is below, yields conflicting eslint dependencies

Ah ok, thanks! I use Yarn, perhaps this is needed since npm presumably isn't reading the `yarn.lock` file then.

**Pull request merged**
