### PR TITLE
Extend `dedup` to check and dispose duplicate materials

### PR DESCRIPTION
**Pull request by MrMagicPenguin**
Directly related to #405. Extend [`dedup`]() to check for duplicate materials and reassign/dispose of duplicates.

### CODE REVIEW

**Comment by MrMagicPenguin** [comment]
Since this relies on #405 being merged first and therefore has duplicate code changes to that PR, is there a more appropriate way to handle this PR?

Cheers!

**Comment by donmccurdy** [comment]
Thanks! I've merged the changes from #405 but you may need to rebase or resolve conflicts here.

**Comment by MrMagicPenguin** [comment]
Cheers! I will address that shortly, I think I must have rushed that PR. Sorry

**Comment by MrMagicPenguin** [comment]
Hi friend @donmccurdy , just hoping to bump this as this is a roadblock for my own script. I dont mean to rush you: i appreciate that this is open source and therefore means you putting your time in to benefit all of us for free.

All the best

**Comment by donmccurdy** [comment]
Ah sorry, I didn't realize this was ready for review again – do feel free to post a comment after pushing commits, that's helpful for me to know as well! I'll have a closer look at this soon. 👍

**Comment by MrMagicPenguin** [comment]
Oh okay, will do! I didnt realise you wouldn't be notified. Thanks again!

**Comment by donmccurdy** [comment]
Thank you! The implementation in `dedup()` looks perfect, I've merged this as https://github.com/donmccurdy/glTF-Transform/commit/f69517b8fd30a05ddc728ad5b28c5d59ff16c5c6 and added a short test case in https://github.com/donmccurdy/glTF-Transform/commit/963226e36269111ad678b31b1a3d0e942ee44698.

**Pull request closed without merging**
