### PR TITLE
Add sortPrimitiveWeights()

### LINKED ISSUE #668: Normalize Skin Weights exposed as function
**Is your feature request related to a problem? Please describe.**
I often get GLB assets that have many  `ACCESSOR_WEIGHTS_NON_NORMALIZED` errors and produce visual errors in some apps.

**Describe the solution you'd like**
Expose [normalizeWeights](https://github.com/donmccurdy/glTF-Transform/blob/18c475741a35cc5c79af2617fcec4d2ac82bf1a8/packages/functions/src/quantize.ts#L434-L468) as a function to use in scripts and CLI.

**Describe alternatives you've considered**
Round-trip through blender, and re-export, but that would be slow and maybe affect other areas of the file (e.g. missing extension support).

[Discussed here](https://github.com/donmccurdy/glTF-Transform/discussions/667) before.

### LINKED ISSUE #669: Limit deform weights associated with a vertex to a specified number by removing lowest weights
**Is your feature request related to a problem? Please describe.**
A more efficient file would only have WEIGHTS_0 & JOINTS_0 as vec4 for skin weights. According to the 2.0 specs, 

> Client implementations MAY support only a single set of up to four weights and joints

**Describe the solution you'd like**
It would be great to have a function exposed to scripts and CLI that would limit the weights per vertex to the 4 most influential ones (or variable number). That would mean reordering WEIGHTS_n to put largest into WEIGHTS_0 and then reordering JOINTS_n accordingly. Then discard WEIGHTS_1+ & JOINTS_1+. Lastly, weights should be re-normalized.

### PR DESCRIPTION
**Pull request by donmccurdy**
Related:

- Fixes #669 
- Fixes #668 

Example:

```javascript
const limit = 4;

for (const mesh of document.getRoot().listMeshes()) {
  for (const prim of mesh.listPrimitives()) {
    sortPrimitiveWeights(prim, limit);
  }
}
```

Remaining:

- [x] ~~unit tests~~
- [x] ~~documentation~~
- [x] ~~update normalizePrimitiveWeights() for new usage~~
- [ ] ~~rename? sortSkinWeights()?~~

### CODE REVIEW

**Comment by Olaf-Wolf3D** [comment]
Hey, thanks a lot! Earliest I'll be back at a PC will be Sunday. In the meantime I dug up a [glb file](https://www.datocms-assets.com/36636/1616787886-outfit-f-casual-01-v2.glb) that has non-normalized weights, and 2 weight attributes (8 influences) in the mesh `Wolf3D_Outfit_Top`.

**Comment by donmccurdy** [comment]
Thanks @Olaf-Wolf3D! The `sortPrimitiveWeights(prim, limit)` function seems to be working as expected for this sample, so I'll go ahead and merge the PR. Please let me know if you have any issues. I did find that the `quantize()` function fails on this example, which I've filed separately in #673.

**Comment by donmccurdy** [comment]
Published in v2.4.2 —

https://gltf-transform.donmccurdy.com/functions.html#sortprimitiveweights

**Pull request merged**
