### PR TITLE
fix(simplify): Correct usage of 'target_index_count'

### LINKED ISSUE #1263: Simplify breaks due to assertion failed
**Describe the bug**

I'm running into a bug where `gltf-transform simplify` from the command line breaks with an assertion failed error.

Upon closer examination, it looks like this error is coming from this line here (from the meshopt simplify function):
https://github.com/zeux/meshoptimizer/blob/master/js/meshopt_simplifier.js#L178 , where `targetCount > indices.Length` after one iteration therefore failing the assertion.

One thing I did notice from the example of simplify here: https://github.com/zeux/meshoptimizer/blob/master/demo/simplify.html -- it looks like the `targetCount` is calculated based on index count and not the vertex position count as used by gltf-transform. I'm wondering if this is intended, and whether that relates to the bug?

**To Reproduce**
I'm unable to share the model I was testing with, but I'll see if I can recreate the bug with another model.

**Versions:**
 - Version: `cli.js 4.0.0-alpha.5 — Command-line interface (CLI) for the glTF Transform SDK.`
 - Environment: Command line

Thanks!

### PR DESCRIPTION
**Pull request by donmccurdy**
- fixes #1263

### CODE REVIEW

**Comment by donmccurdy** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/donmccurdy/glTF-Transform/1268?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #1267** <a href="https://app.graphite.dev/github/pr/donmccurdy/glTF-Transform/1267?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1268** <a href="https://app.graphite.dev/github/pr/donmccurdy/glTF-Transform/1268?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/donmccurdy/glTF-Transform/1268?utm_source=stack-comment).

**Comment by donmccurdy** [comment]
@marwie very likely this would fix the discrepancy in the ratio (50% vs 90%), yes. I think it is unrelated to the error metric, though.

**Comment by marwie** [comment]
Thank you. I've updated to latest 3 release today but perhaps it's worth updating to 4 already then. From the roadmap it seems like there are no breaking changes https://github.com/donmccurdy/glTF-Transform/issues/1136

**Comment by donmccurdy** [comment]
I haven't written the changelog for v4 yet, but so far the breaking changes are minimal. Some options renamed, or with different default values. If you're using TypeScript, it should catch things. The larger breaking change in v4 will be #1141, which requires a (hopefully small) change to extension implementations. See the changes to EXT_mesh_gpu_instancing in that PR, for an example.

This fix could be patched to a v3.10.x release safely, if that's better.

**Comment by donmccurdy** [comment]
Published to published v3.10.x. ✅ 

#1141 is not on the alpha release yet — everything on the alpha release has already been merged to the `main` branch. See https://github.com/donmccurdy/glTF-Transform/milestone/28 for the full list of what's in the alpha vs. still planned.

**Comment by marwie** [comment]
Thanks a lot! Time to update then 😎

**Pull request merged**
