### PR TITLE
Add PNG/JPEG/WebP optimization via Squoosh CLI

### LINKED ISSUE #12: [texture] JPEG/PNG optimization
Pending https://github.com/GoogleChromeLabs/squoosh/issues/280.

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #12.

Remaining:

- [ ] Documentation
- [ ] Improve defaults, e.g. for normalTexture
- [ ] Unit tests

### CODE REVIEW

**Comment by donmccurdy** [comment]
Not planning to finish this.

**Comment by simonihmig** [comment]
> Not planning to finish this.

@donmccurdy can you explain why? Is it "just" lack of time (in which case others could pick this up?), or any other reason?

I have a need for this, so wanted to create a tool that will basically do this (based on `gltf-transform`), before I stumbled upon this previous effort. For me, a tool that "just works" (no test coverage or documentation) would be enough for now. But if there is interest in upstreaming that work, I might look into that as well. 

As we are at it: what was the reason to use squoosh here? I haven't used it before, but I do have some experience with [sharp](https://github.com/lovell/sharp), so would have picked that one for image processing.

**Comment by pfortes** [comment]
i have been thinking about this also!!

i would love to help!

**Comment by donmccurdy** [comment]
Hi! I closed this PR because I didn't want to include more features here that were only going to work in a Node.js environment. This PR depended on the squoosh CLI, and at the time there wasn't a platform-agnostic option, so I closed the PR.

More recently squoosh has an npm package (`@squoosh/lib`), which still currently only works in Node.js, but they're working on getting it to work on the Web as well: https://github.com/GoogleChromeLabs/squoosh/issues/1084. I'd be interested in a PR similar to this one, using `@squoosh/lib` instead of the CLI, if either of you wanted to give that a shot!

**Comment by donmccurdy** [comment]
Continued in https://github.com/donmccurdy/glTF-Transform/pull/506!

**Pull request closed without merging**
